///|
pub using @core {type QObject, trait AsObject, type Signal, type Connection}

///|
pub using @widgets {
  trait AsAbstractButton,
  trait AsBoxLayout,
  trait AsFrame,
  trait AsLayout,
  trait AsWidget,
  type QAbstractButton,
  type QApplication,
  type QBoxLayout,
  type QFrame,
  type QHBoxLayout,
  type QLabel,
  type QLayout,
  type QLineEdit,
  type QPushButton,
  type QVBoxLayout,
  type QWidget,
}
